My Gallary challenge
aliakhizer/dev-challenges pull request #1
Opened 2023-09-01 10:07 UTC by aliakhizer

This page has two sections. 
The first section is for Profile Details where I have used (one-dimensional)Flex to display the
1)Image
2)Title
3)post details  profile 
The second section is for Gallery Photos where I have added photos in a two-dimensional layout (grid).
## desktop view
![image](https://github.com/aliakhizer/dev-challenges/assets/70663472/667a9456-d83e-4b24-9fc8-0349823a4ebf)
## mobile view
![image](https://github.com/aliakhizer/dev-challenges/assets/70663472/d3782e35-7289-4899-b85e-1413d46692cd)

2023-09-01 10:36 UTC, naumanzchaudhry commented
> This page has two sections. The first section is for Profile Details where I have used (one-dimensional)Flex to display the 1)Image 2)Title 3)post details profile The second section is for Gallery Photos where I have added photos in a two-dimensional layout (grid).
> 
> ## desktop view
> ![image](https://user-images.githubusercontent.com/70663472/264991517-667a9456-d83e-4b24-9fc8-0349823a4ebf.png)
> 
> ## mobile view
> ![image](https://user-images.githubusercontent.com/70663472/264991670-d3782e35-7289-4899-b85e-1413d46692cd.png)

Text description at the top is not completely readable. Please fix this

2023-09-01 10:40 UTC, naumanzchaudhry commented on my-gallary/styles.css
> +.grid-items5 {
Why are these classes empty. If they are not needed, should be removed

2023-09-01 10:40 UTC, naumanzchaudhry commented on my-gallary/styles.css
> +  color: #b9bdcf;
Are we not using css variables?

2023-09-01 10:41 UTC, naumanzchaudhry requested changes
Please fix mentioned changes

2023-09-01 11:05 UTC, aliakhizer commented
I delete it, it's not needed, I mentioned it just for my understanding...

On Fri, Sep 1, 2023, 3:41 PM Nauman Zafar ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please fix mentioned changes
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/aliakhizer/dev-challenges/pull/1#pullrequestreview-1606708283>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ3D2MH2ADJSIZAEYXOYSYDXYG3W7ANCNFSM6AAAAAA4HKWKS4>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-09-01 11:12 UTC, aliakhizer commented
I have used 2 css custom  variables.. for color and border radius..

On Fri, Sep 1, 2023, 4:05 PM Alia Khizer Hayat ***@***.***>
wrote:

> I delete it, it's not needed, I mentioned it just for my understanding...
>
> On Fri, Sep 1, 2023, 3:41 PM Nauman Zafar ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Please fix mentioned changes
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/aliakhizer/dev-challenges/pull/1#pullrequestreview-1606708283>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQ3D2MH2ADJSIZAEYXOYSYDXYG3W7ANCNFSM6AAAAAA4HKWKS4>
>> .
>> You are receiving this because you were assigned.Message ID:
>> ***@***.***>
>>
>

2023-09-03 09:53 UTC, hariscs requested changes

2023-09-03 09:53 UTC, hariscs commented on my-gallary/index.html
> +      </div>
use semantic HTML, eg `header`

2023-09-03 09:53 UTC, hariscs commented on my-gallary/index.html
> +            <p>Posts</p>
both of them should be `span` tags

2023-09-03 09:53 UTC, hariscs commented on my-gallary/styles.css
> +  font-family: "Montserrat", sans-serif;
use css variables for font-family

2023-09-03 09:53 UTC, hariscs commented on my-gallary/styles.css
> +}
css class names should be meaningful

2023-09-03 09:53 UTC, hariscs commented on my-gallary/styles.css
> +}
add classes to these elements istead od targeting the element direclty

2023-09-03 09:53 UTC, hariscs commented on my-gallary/styles.css
> +.box1 {
don't use numbers in class names

2023-09-03 09:53 UTC, hariscs commented on my-gallary/styles.css
> +  /* max-width: 280px; */
remove unused code

2023-09-04 13:49 UTC, hariscs approved these changes

2023-09-05 10:24 UTC, merged